version: "3.9"

services:
  django-backend:
    build:
      context: ./backend
    container_name: django-backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    networks:
      - app-network

  react-frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://43.205.115.180:8000
    depends_on:
      - django-backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
