
name: CI/CD - Build, Push & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------------- Docker Login ----------------
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # ---------------- build & push Backend ----------------
      - name: Build & Push Django Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/django-backend:latest

      # ---------------- build & Ppush Frontend ----------------
      - name: Build & Push React Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/react-frontend:latest

      # ---------------- Deployment to AWS EC2 ----------------
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          timeout: 120s
          debug: true
          script: |
            set -e
            cd /home/devops/devops-assessment

            git pull origin main

            echo "Checking backend image..."
            if ! docker pull ${{ secrets.DOCKERHUB_USERNAME }}/django-backend:latest; then
            echo "Backend image not found. Will build locally."
            fi

            echo "Checking frontend image..."
            if ! docker pull ${{ secrets.DOCKERHUB_USERNAME }}/react-frontend:latest; then
            echo "Frontend image not found. Will build locally."
            fi

            docker-compose down

            echo "Starting deployment..."
            docker-compose up -d --build

          
