
name: CI/CD - Build, Push & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      # ---------------- Checkout Code ----------------
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------------- Docker Login ----------------
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # ---------------- Build & Push Backend ----------------
      - name: Build & Push Django Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/django-backend:latest

      # ---------------- Build & Push Frontend ----------------
      - name: Build & Push React Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/react-frontend:latest

      # ---------------- Deployment to AWS EC2 ----------------
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: rushi                   
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            # Navigate to the directory containing docker-compose.yml
            cd /home/devops/devops-assessment

            # Pull the latest images
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/django-backend:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/react-frontend:latest

            # Bring down any running containers
            docker compose down

            # Start containers in detached mode
            docker compose up -d
